jda:
  enabled: false
  token: "___.___.___"
  link-channel: 000000000000000000
  console-channel: 000000000000000000
  webhook: "https://discord.com/api/webhooks/...."

logging:
  log-error: true
  log-info: true
  log-debug: false
  notify-ops-on-error: true

computing:
  disable-computers: false
  privileges:
    chunkloading: false
    net: false

authorization:
  microsoft:
    spoof-ms-server: true
    client-id: "chat is this real"
    client-secret: "this is so real"
  jwt:
    secret-key: randomize-on-server-start
    secret-key-is-password: false

services:
  blazing-api:
    enabled: false
    find-at: "http://localhost:8080"
    bind:
      port: 8080
      https:
        enabled: false
        password: "enter super secret and secure password here"
        file: localhost.p12
    proxy:
      in-use: false
      ip-address-header: CF-Connecting-IP
      allow-all: false
      allowed-ipv4: []
      allowed-ipv6: []
  blazing-wss:
    enabled: false
    find-at: "http://localhost:9090"
    bind:
      port: 9090
      https:
        enabled: false
        password: "enter super secret and secure password here"
        file: localhost.p12
    proxy:
      in-use: false
      ip-address-header: CF-Connecting-IP
      allow-all: false
      allowed-ipv4: []
      allowed-ipv6: []

docs:
  official-instance:
    name: Blazing Console
    url: https://console.bedcrab.dev
  user-links:
    - name: Discord
      url: "#"
  developer-links:
    - name: Support
      url: "#"
    - name: Bug Tracker
      url: "#"
  notice:
    show: true
    title: Change (or disable) this notice bar in the config.yml
    description: Show important announcements or links here
    button-title: Customizable link button
    button-url: "#"